### ISSUE TITLE
Request: RemoteUI: Open and add items to multibuy

### ISSUE THREAD

**Issue by SciFi-Bob** [ccpgames/esi-issues#206] opened 2017-01-10 21:36 UTC
When you get to implementing the option that exists in CREST to open the market window to an item in the game client please can we have the option to send a list of items and pop a multi buy.

Thanks

**Comment by CarbonAlabel** [comment] 2017-01-11 06:00
Duplicate of #54?

**Comment by defmonk0** [comment] 2017-01-11 09:43
Should be a duplicate, yea. After my clarification over there, this is what was asked for - indiscriminate access to open and add things to the buy-all window.

**Closed** 2017-01-11 16:03 UTC
Labels: New
