### ISSUE TITLE
Feature Request: Retrieve/update block list via ESI

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#390] opened 2017-05-12 14:55 UTC
# Feature Request

I would like to be able to retrieve and update a character's blocklist via ESI (so I can propagate it between characters).

It appears that blocked characters aren't necessarily included in the existing contacts endpoint Characters.get_characters_character_id_contacts()

(I just retrieved several hundred contacts from ESI, but not one of them was listed as blocked. Its possible that this is a bug, in which case this issue should not be a feature request)

## Proposed route

Characters.get_characters_character_id_blocklist()

Additional routes to post a new character to block, or put a character to unblock.

### Use case

I have blocked unsavoury characters on several different characters, but I have a different set of blocked characters on each of my characters. I wish that when I blocked a deplorable on one character, it would also be blocked on another character - i.e. I wish I had exactly the same list of blocked characters on all of my characters.

### Example returns

    [ 
      {
        contact_type : 'character',
        contact_id : 12345,
      },
    ]

**Comment by aquarhead** [comment] 2017-08-29 14:42
Duplicate of #231

**Closed by aquarhead** 2017-08-29 14:42 UTC
Labels: esi-contacts, feature request
