### ISSUE TITLE
esi-universe: regions

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#24] opened 2016-11-09 16:43 UTC
https://trello.com/c/Tg0Kf8QF/22-esi-universe-regions

**Comment by gitAskur** [comment] 2016-11-11 09:53
monolit action get_regions_v1 added for support

**Comment by ccpStuart** [comment] 2016-12-06 15:21
Duplicate of https://github.com/ccpgames/esi-issues/issues/25

**Comment by tsuthers-ccpgames** [comment] 2016-12-07 13:34
closing because duplicate

**Closed by tsuthers-ccpgames** 2016-12-07 13:34 UTC
Labels: esi-universe, TODO
