### ISSUE TITLE
/v1/characters/{character_id}/industry/jobs/ include_completed has no effect

### ISSUE THREAD

**Issue by Conjur0** [ccpgames/esi-issues#415] opened 2017-05-27 06:31 UTC
# Bug
/v1/characters/1120048880/industry/jobs/?datasource=tranquility&include_completed=false

include_completed seems to have no effect. regardless if it's omitted, set to true, or false; ESI still returns several hundred delivered jobs.

**Comment by GoldenGnu** [comment] 2017-05-27 10:06
It also, does not include all jobs (No matter what include_completed is set to).
I have a very old job (I use it to test jEveAssets) and it's not included in ESI, but, It's include in the XML API

### Response
ESI:
```[]```

XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<eveapi version="2">
  <currentTime>2017-05-27 09:57:58</currentTime>
  <result>
    <rowset name="jobs" key="jobID" columns="jobID,installerID,installerName,facilityID,solarSystemID,solarSystemName,stationID,activityID,blueprintID,blueprintTypeID,blueprintTypeName,blueprintLocationID,outputLocationID,runs,cost,teamID,licensedRuns,probability,productTypeID,productTypeName,status,timeInSeconds,startDate,endDate,pauseDate,completedDate,completedCharacterID,successfulRuns">
      <row jobID="280477676" installerID="987623974" installerName="Golden Gnu" facilityID="60014818" solarSystemID="30003416" solarSystemName="Aldrat" stationID="60014818" activityID="1" blueprintID="231144695" blueprintTypeID="1146" blueprintTypeName="Iron Charge L Blueprint" blueprintLocationID="60014818" outputLocationID="60014818" runs="1" cost="84.00" teamID="0" licensedRuns="200" probability="1" productTypeID="231" productTypeName="Iron Charge L" status="1" timeInSeconds="720" startDate="2015-11-20 12:49:16" endDate="2015-11-20 13:01:16" pauseDate="0001-01-01 00:00:00" completedDate="0001-01-01 00:00:00" completedCharacterID="0" successfulRuns="0"/>
    </rowset>
  </result>
  <cachedUntil>2017-05-27 10:01:05</cachedUntil>
</eveapi>
```

### Expected
ESI should include the same jobs as the XML API

**Comment by aquarhead** [comment] 2017-09-18 13:53
Sorry, I just saw this, marking this as a duplicate of #563 I already fixed it and it's staging.

**Closed by aquarhead** 2017-09-18 13:53 UTC
Labels: bug, esi-industry
