### ISSUE TITLE
esi-bookmarks: delete and rearrange bookmarks

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#12] opened 2016-11-09 16:43 UTC
https://trello.com/c/78EyFXa2/42-esi-bookmarks-delete-and-rearrange-bookmarks

**Comment by ccpStuart** [comment] 2016-12-06 15:15
reviewed

**Comment by ccpStuart** [comment] 2016-12-06 15:30
Duplicate of https://github.com/ccpgames/esi-issues/issues/69

**Closed by ccpStuart** 2016-12-06 15:30 UTC
Labels: Backlog, esi-bookmarks

**Comment by gitAskur** [comment] 2017-05-31 09:55
You crawl further and further down the dark recesses of the cavern, but soon reach a dead end. When you turn around to go back the way you came you realize that what now lies behind you is not the cavern you just passed through but something entirely different.

Go to #69 to continue on your journey!
