### ISSUE TITLE
Request: Add more details to /universe/systems/{system_id}/

### ISSUE THREAD

**Issue by shibdib** [ccpgames/esi-issues#163] opened 2016-12-14 17:23 UTC
Jumps per 24h... etc... stuff that can be see using the ingame map

**Comment by Regner** [comment] 2016-12-14 17:44
Might be better to have a stats endpoint that lists the stats for all solar systems

**Comment by shibdib** [comment] 2016-12-14 19:38
This would also work

**Comment by Robbilie** [comment] 2017-01-21 13:04
@shibdib would you mind changing the feature request to creating a dedicated stats endpoint?
maybe per system, maybe global (like the jumps/kills api in xml)
pilots in space would be a nice stat to add here aswell

**Comment by Robbilie** [comment] 2017-01-29 15:46
this here is actually a duplicate of andis request:
https://github.com/ccpgames/esi-issues/issues/86

**Comment by aquarhead** [comment] 2017-03-27 14:19
Closing in favor of #86 which is in staging now

**Closed by aquarhead** 2017-03-27 14:19 UTC
Labels: esi-universe, feature request, TODO
