### ISSUE TITLE
Feature request: Add Character Type ID to /characters/{character_id}/

### ISSUE THREAD

**Issue by lukasni** [ccpgames/esi-issues#905] opened 2018-05-09 23:19 UTC
# Feature Request

There are Type IDs for the different possible combinations of Race and Bloodline, represented in the Type IDs 1373 to 1386. Currently the only way of finding the correct type id for a character is to pull details on these types, reading the description and building a lookup table from that. It would be nice to have that info added to the public character data endpoint.

## Use case

A characters type id is required to make an info link to be used in game, format `<url=showinfo:{type_id}//{character_id}>Name</url>`, for example to use in a mail body.

## Authentication

Extends a public route, no auth required.

## Example return

```json
{
  [...],
  "type_id": 1373
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [x] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by CarbonAlabel** [comment] 2018-05-10 06:16
#210

**Comment by CarbonAlabel** [comment] 2018-05-10 07:46
Also, this specific use case isn't really valid, as you don't need to use the exact type ID of the character you are trying to link; the EVE client will properly recognize the `showinfo` link as long as you're using any type ID from the [Character group](https://esi.evetech.net/dev/universe/groups/1/).

**Comment by ccp-zoetrope** [comment] 2018-05-11 10:54
Closing because it is a duplicate of https://github.com/ccpgames/esi-issues/issues/210.

**Closed by ccp-zoetrope** 2018-05-11 10:54 UTC
