### ISSUE TITLE
[Bug] PUT /fleets/{fleet_id}/ accepts CREST parameter name

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#893] opened 2018-05-01 19:48 UTC
# Bug
`PUT /fleets/{fleet_id}/` accepts CREST `new_settings` parameter name `isFreeMove`, when it should instead error if the parameter names aren't `is_free_move` or `motd`.  
The `isFreeMove` value is silently ignored. The corrected `is_free_move` works to alter the in-game setting (though in-game fleet history doesn't show this change).

### Request
`PUT /fleets/{fleet_id}/`
`{
  "isFreeMove": true,
  "motd": "string"
}`

### Response
204 Fleet updated

### Expected
400 Bad request

**Comment by tsuthers-ccpgames** [comment] 2018-05-02 16:02
Hrm, it looks like the PUT body isn't being rigidly validated. I can add random keys and it doesn't protest. I can also remove the is_free_move key without problems despite that key ostensibly being mandatory.

So two problems:
1. Why is the endpoint not erroring if required fields are not included?
2. Does ESI in general ignore extra keys not in the spec? If yes, should it maybe throw an error instead?

@a-tal do you know if #2 is standard behavior? save me from testing a bunch of random endpoints?

**Comment by a-tal** [comment] 2018-05-02 16:04
the request as posted is valid. it'll change the motd only (`is_free_move` is optional)

esi validation tosses nonsense parameters, both during input and response validation.

not a bug

**Comment by tsuthers-ccpgames** [comment] 2018-05-02 16:06
Oh, you're right, it is optional, reading is hard.

**Comment by tsuthers-ccpgames** [comment] 2018-05-02 16:15
So TL;DR this is a corner case caused by the combination of:
a) ESI discarding incorrect keys
b) All the attributes of that PUT body being optional

This creates the confusing case where any typo made in the body will be silently accepted. I personally would vote to have the endpoint return a warning header stating that the body was not strictly compliant but was accepted anyway in this case, because I like to be told when I do things wrong.

**Comment by a-tal** [comment] 2018-05-02 16:39
going to close this as `invalid`. this is actually a great example of why you should use a swagger client, this type of error is easy to catch client-side based off the spec.

am going to leave this behaviour as is. if people really want to change this, open a new issue and maybe link to this one from there

**Closed by a-tal** 2018-05-02 16:39 UTC
Labels: conventions, esi-fleets
