### ISSUE TITLE
Character blueprint endpoint only returns 500 results instead of everything

### ISSUE THREAD

**Issue by Kyria** [ccpgames/esi-issues#526] opened 2017-08-24 09:21 UTC
# Bug

Currently, when you query the [character/blueprint](https://esi.tech.ccp.is/ui/#/Character/get_characters_character_id_blueprints) endpoint you only get a maximum of 500 blueprints, even if there are more.

I tested with my character, who owns a little 1546 blueprints (copy/originals) according to XML API (which returns the full list)

[According to @ccp-zoetrope on slack](https://tweetfleet.slack.com/archives/C30KX8UUX/p1503565184000153):
> for that endpoint in particular it is restricted in the monolith side though and it looks to be that it only returns 500 items max honestly

### Request

https://esi.tech.ccp.is/ui/#/Character/get_characters_character_id_blueprints 

### Response

A list containing only 500 blueprints

### Expected

A list containing the complete list of blueprints.

Thanks !

Edit: looks like a duplicate of #443...

**Comment by aquarhead** [comment] 2017-08-24 10:16
Duplicate of #443

**Closed by aquarhead** 2017-08-24 10:16 UTC
