### ISSUE TITLE
Location Endpoint Returning Bad ID

### ISSUE THREAD

**Issue by themightymanuel** [ccpgames/esi-issues#338] opened 2017-04-04 23:44 UTC
The Location endpoint has started returning region IDs where the system ID is supposed to be. As of right now it is for sure happening in Sotrentaira. Will test other systems soon.

**Comment by Robbilie** [comment] 2017-04-04 23:52
region or constellation ids…?
can you reproduce this? we noticed this issues today, especially damian from tripwire :)

**Comment by themightymanuel** [comment] 2017-04-05 00:48
sorry constellation ids

**Comment by themightymanuel** [comment] 2017-04-05 00:50
it works now that I am in station the issue was previously while in space. I will try to reproduce again later in different situations etc. later but right now I can't log in for a bit.

**Comment by themightymanuel** [comment] 2017-04-05 01:29
OK tested it in a few other systems:
Uemisaisen and Ouranienen both return:
{"solar_system_id": 20000200}
Autama returns:
{"solar_system_id": 20000207}

This is only happening while in space when in station it behaves normally.

**Comment by gitAskur** [comment] 2017-04-05 15:00
I am having no luck reproducing this locally, and the monolith code has no obvious code paths, and lots of obvious conditionals checking if the value ain't a valid systemID. So any information that anyone can provide is much appreciated.

**Comment by Robbilie** [comment] 2017-04-05 15:17
to retrieve the solar_system_id, is it traversing the "tree" top to bottom or bottom to top?
player -> ship -> system
universe -> region -> constellation -> system

?

as reported, when in station its reported correctly aka
player -> ship -> station -> system (correct)
player -> ship -> system (not correct)

**Comment by gitAskur** [comment] 2017-04-05 15:24
Neither, legacy issues prevent me from trusting any such traversal. I'm pretty sure this is connected with these legacy issues. Except where they don't and then you could describe the relationships in play as traveling down a tree.

I need information such as if the character is online, was offline at the first time of ESI query but has since then come online and everything was fine until another state was set, etc. etc. So I can start stupid guesses, because sensible guesses are not going to take us very far other than down the road of cursing things for not being as we'd want them.

**Comment by Robbilie** [comment] 2017-04-05 15:43
just traverse, collect all ids and type check all of them and filter for system id xD

**Comment by gitAskur** [comment] 2017-04-05 15:46
Aaand walking home I realized this is maybe something to do with structures. They might again have introduced a meaningful reason for locating a character in them, rather than a ship, and they have none of the characteristics of a station when it comes to the code, where they just look like a ship unless groups are checked. So I might very well have used some optimizations to check for the location type, which will treat structures as ships, and thus return the locationID of the locationID as the system, thinking it is doing a char.locationID -> ship.locationID -> station/structure.loationID => solar system ID traversal, but is actually doing a char -> station/structure.locationID -> solar system.locationID => constellationID traversal.

But that relies on there being a meaningful reason for setting a characters locationID as a structureID because structures were not a thing when that became a valid state the first time around. I'll need to look at that. But if you could keep an eye out for structures being thrown in the mix and things getting wonky, that would be great :)

**Comment by Robbilie** [comment] 2017-04-05 15:48
yeah thats what i thought, if its that, at least we know now what it is and you just have to find the corresponding code snippet :P

**Comment by Robbilie** [comment] 2017-04-05 15:50
@themightymanuel can you check what happens when you are in a structure?
you said:
in space -> incorrect
in station -> correct
in citadel -> …?

**Comment by gitAskur** [comment] 2017-04-05 15:50
The code itself is super simple, and I wrote it myself a month ago or so. The potential states is something I cannot read from just looking at my code, and becomes a mess of how tons of different things interact together.

If it wasn't in the base inventory system, I'd be fine with throwing in all sorts of checks and balance and make sure this is all up to snuff, but then the entirity of EVE's inventory system slows down due to this single use case and that I am not cool with.

**Comment by gitAskur** [comment] 2017-04-05 15:55
Two things that come to mind are:
Pod Death -> cloned to structure -> no undock or ship changes before server goes down -> server goes up -> ESI queried before logon => constellationID present as systemID until the first system jump (not undock).

Or being in control of the citadel when the server goes down -> server goes up -> same as above.

And, there is a locking conflict out on TQ, fixed in staging and out on tuesday, now that could then prevent updates from happening so the constellationID persists.

**Comment by Robbilie** [comment] 2017-04-05 15:55
manuel confirmed in citadel returning correct last night

**Comment by gitAskur** [comment] 2017-04-05 15:56
goddamnit Manuel!

**Comment by gitAskur** [comment] 2017-04-05 16:00
Can someone confirm that it happened without any "hostile session changes" happening? Hostile being "teleports" rather than jumps or docks/undocks (Wormholes are still jumps). Or that it wasn't happening until such a session change as well. Or both... preferably not both tho because that just confuses me more.

**Comment by themightymanuel** [comment] 2017-04-05 16:31
Im not home right now but last night i tried 
Authenticating in space > location fails 
Authenticating in station > location works > undock > location fails
Jumped gate > autenticated > location fails 

Didnt try logging off and then back in space. Also didnt test while logged off in space.

**Comment by gitAskur** [comment] 2017-04-05 17:11
Authenticating in station > location works > undock > location fails

If that's consistent for you then my issue must be my local server and that's good enough to take me places.

**Comment by themightymanuel** [comment] 2017-04-05 18:51
Hopefully it's functional soon. If you need me to test anything just give me a list of steps.

**Comment by gitAskur** [comment] 2017-04-06 09:41
This mystery has been demystified. Expect a fix to hit TQ on Tuesday the latest. I'll try and get it out asap but it's fanfest and I've drunk all the favours people owe me.

**Comment by Robbilie** [comment] 2017-04-06 11:34
Story time? :P

**Comment by gitAskur** [comment] 2017-04-06 11:57
I just got a new workstation on Monday. I was the problem. 

I hadn't synced all the branches I needed to sync before starting to investigate this, so I was using our ESI sandbox which is usually always up to date but wasn't in this exact instance because I was setting up my new workstation and not doing my daily integrates.

I realized this after Manuel described the easy repro steps for him. There was no way that this was impossible for me to repro while merely jumping would expose the issue to him. Then, after some time of syncing code, this morning I looked at the code that was obviously sound in the ESI sandbox and it literally read

solarSystemID = destinationRecord.locationID

which is obviously not going to work in the case of the destinationRecord being a system item, since they are located in constellations.

So.. basicly  looking at the actual code was the solution. I feel silly but it's okay because I have a new workstation.

**Comment by Robbilie** [comment] 2017-04-06 12:02
well you know why i think this is ok?
because you quickly responded, transparently documented your work and explained us what you were doing and all of this in a quick, interactive way :)
its fixed and in a nice way, thanks :D

**Comment by gitAskur** [comment] 2017-04-06 12:16
Thanks man :)

**Comment by paulheu** [comment] 2017-04-07 06:24
It may be FanFest and all but how does that excuse not pusing through a critical (IMO) fix which quite a few people depend on. Not personal man, but I heard the usual blahblah on the keynote where apparently the party and booz would have priority over getting the product working as intended, especially with a fix in place which 'just' needs to be pushed out.

**Comment by gitAskur** [comment] 2017-04-07 08:23
It's not an "excuse" not to push stuff through. It's a "reason" for why I cannot get people to break the usual deployment procedure of Tuesdays or Thursdays, and push it out asap. They are busy with Fan Fest stuff and I have no claim on their free time to come do stuff for me for my reasons.

I understand that you're not happy with the focus being what it is, but this is directed in the totally wrong direction. I have no authority to address those concerns, and despite this not being something personal, I don't think you're being very fair to me.

**Comment by gitAskur** [comment] 2017-04-11 11:09
This should be out on TQ now.

**Closed by gitAskur** 2017-04-11 11:09 UTC
Labels: bug, Done, esi-location

**Comment by Suprano** [comment] 2017-04-11 11:25
Confirm that it is working for ESI.

Thanks Askur 👍
