### ISSUE TITLE
No parity for /eve/CharacterID.xml.aspx

### ISSUE THREAD

**Issue by skyride** [ccpgames/esi-issues#627] opened 2017-10-31 16:17 UTC
# Inconsistency
The XML to ESI migration sheet [claims](https://github.com/ccpgames/esi-issues/blob/master/XML_to_ESI.md#characterid) that this is fulfilled by using the Search feature in ESI with certain parameters, but this is simply not the case. The primary use case for the original endpoint was bulk character ID lookups, up to multiple thousands.

A common application of this is the various "local scan" tool where the character list in local is copied from ingame and pasted into a tool to resolve corporations, alliances, plus potential killboard activity.

Using XML, this pattern was achieved by 1 call to, `/eve/CharacterID.xml.aspx` and another to `/eve/CharacterAffiliation.xml.aspx`. However under ESI, this pattern now requires hundreds if not thousands of API calls.

The affiliation endpoint itself can be batched into a single query, but a call will now require at least one hit to search per character, and potentially another to GET character, corporation, alliance and faction. This means that taking a local scan of Jita on a busy Saturday would previously have generated 2 calls that took 5-10s to execute, while now we'll be looking at between 5,001 and 12,501.

### Request
The char/corp/alliance/faction data can be cached, but we need a POST endpoint that can resolve names to characterIDs in bulk.

**Comment by aquarhead** [comment] 2017-11-02 19:29
Duplicate of #27

**Closed by aquarhead** 2017-11-02 19:29 UTC
Labels: parity
