### ISSUE TITLE
/characters/{character_id}/orders/ cache timer

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#497] opened 2017-07-27 17:37 UTC
# Feature request

### Route
/characters/{character_id}/orders/

### Authentication
esi-markets.read_character_orders.v1

### Use case
Could we get the cache timer for this endpoint lowered to 5min to match the /markets/structures/{structure_id}/ endpoint?  Having up to date, near real time information about your market orders could be useful.

**Comment by aquarhead** [comment] 2017-08-11 16:40
Duplicate of #468

**Closed by aquarhead** 2017-08-11 16:40 UTC
Labels: New
