### ISSUE TITLE
ESI HTTP code 500 https://esi.tech.ccp.is/latest/corporations/CORPID/roles/

### ISSUE THREAD

**Issue by swerrie** [ccpgames/esi-issues#226] opened 2017-01-18 22:50 UTC
calling this URL: https://esi.tech.ccp.is/latest/corporations/CORPID/roles/" returns an HTTP code 500 ({"error": "uncaught exception"})".

Something wrong with this endpoint?

**Comment by ddouglas493** [comment] 2017-01-19 03:15
Reference #189

**Comment by swerrie** [comment] 2017-01-19 08:31
Can anyone confirm he is able to access GET /corporations/{corporation_id}/roles/?

It's since yesterday the api returned code 500. My character roles did not change ingame so code 403 UNAUTHORIZED is misplaced.

@ddouglas493 You said you caught the 403 before the 500, how are you able to log that? My response just throws 500.

**Comment by ddouglas493** [comment] 2017-01-19 13:47
I wrote a PHP for loop into my script that tries the call again up to 5x if
the status code doesnt equal 200, and then I log the response in a database
for farther review at a later date. If I don't get a 200, a flag is raised
so attention is brought to it when I review the data.

**Comment by swerrie** [comment] 2017-01-19 14:44
Just tried it out on https://esi.tech.ccp.is

`Request URL

https://esi.tech.ccp.is/latest/corporations/1817710684/roles/?datasource=tranquility

Response Body

{
  "error": "uncaught exception"
}

Response Code

500

Response Headers

{
  "server": "nginx",
  "date": "Thu, 19 Jan 2017 14:42:20 GMT",
  "content-type": "application/json",
  "content-length": "31",
  "vary": "Accept-Encoding",
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET,POST,DELETE,PUT,PATCH,OPTIONS",
  "access-control-allow-headers": "Content-Type,Authorization",
  "access-control-expose-headers": "Content-Type,Authorization",
  "access-control-allow-credentials": "true",
  "x-sentry-id": "19973f4d590e4efa89f5bf0f2eb1aaa9",
  "strict-transport-security": "max-age=31536000",
  "via": "1.1 google",
  "alt-svc": "clear",
  "x-firefox-spdy": "h2"
}`

**Comment by rottjr** [comment] 2017-01-27 07:57
I am receiving the same error

ENDPOINT
https://esi.tech.ccp.is/latest/corporations/98125412/roles/?datasource=tranquility

SENT HEADERS
Authorization: Bearer xxx
Accept: application/json

RAW
{"error": "uncaught exception"}
Status:
500: INTERNAL SERVER ERROR
Loading time: 1991 ms


Server: nginx
Date: Fri, 27 Jan 2017 07:56:08 GMT
Content-Type: application/json
Content-Length: 31
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,DELETE,PUT,PATCH,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization
Access-Control-Expose-Headers: Content-Type,Authorization
Access-Control-Allow-Credentials: true
X-Sentry-Id: 41cce8af80534183ab7bb89c25423874
Strict-Transport-Security: max-age=31536000
Via: 1.1 google
Alt-Svc: clear

Also note I am the director of my corp so no permission issues.

**Comment by ddouglas493** [comment] 2017-03-05 05:22
Please close this as a duplicate of #189

**Closed** 2017-03-17 00:58 UTC
Labels: New
