### ISSUE TITLE
corporation members online state endpoint request

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#52] opened 2016-11-09 23:08 UTC
similar to the membertracking XML API endpoint or the requested online endpoint for a character, this endpoint might be integrated with the existing GET /corporations/{corporation_id}/members/ endpoint to not only include the character_id but also the online state or even the last online state

someone requested something like this a few days ago asking CCP Bartender iirc about a membertracking endpoint with lower cache time to for example check during CTAs who is online but not in fleet or see member online times...

**Comment by Robbilie** [comment] 2016-11-10 14:45
Looking at the current cache time, it might make sense to use a completely new endpoint which would have a lower cache time and would include character_id, online, last_online, location, ship

**Comment by ccpStuart** [comment] 2016-12-06 15:29
Duplicate of https://github.com/ccpgames/esi-issues/issues/10

**Comment by Kupuyc** [comment] 2017-06-27 01:14
Any news?

**Comment by Kupuyc** [comment] 2017-08-09 15:20
Any news?

**Comment by aquarhead** [comment] 2017-08-09 16:21
The ESI parity endpoint of corp MemberTracking will be deployed soon.

**Comment by aquarhead** [comment] 2017-08-29 12:13
https://ccpgames.github.io/esi-issues/XML_to_ESI#membertracking

**Closed by aquarhead** 2017-08-29 12:13 UTC
Labels: Backlog, esi-corporations, feature request

**Comment by Kupuyc** [comment] 2017-08-30 02:17
But... XML::membertracking is not what we asked. We asked online status of corporation members. And 1 hour cache is too long.

**Comment by Aidansavage** [comment] 2017-08-30 02:27
Unfortunately, I'm going to be "that guy" and say real-time access to a character's online/offline state treads too close to "opsec" reasons. This is also exacerbated due to revocation of ESI app permissions being less straightforward than what it is for crest/xml via API keys, hence being able to track characters no longer associated with your corporation or alliance. Plus it'd probably be a hardware issue too since you're not pulling directly from the game servers anyways.

**Comment by Robbilie** [comment] 2017-08-30 09:37
@Aidansavage I dont get how this is too opsec when that data is available ingame and available in the old api. I also dont know whats not straight forward about pressing a "Delete" button. This is a corporation endpoint, it will not allow you to track single characters, therefore once a character leaves the corporation it cant be tracked anymore, the entity that has to grant this esi permission is the ceo or a director in said corporation so this makes zero sense. Esi is basically a proxy to the monolith, i have no idea what you are talking about with your hardware issues.

**Comment by Kupuyc** [comment] 2017-09-05 17:18
@aquarhead How about to reduce cache time? To 5-10 mins. One hour cache makes endpoint absolutely useless. Even 30 mins too long.

**Comment by aquarhead** [comment] 2017-09-05 17:21
What is your use case? If you need up-to-date information for corporation members, please use [these endpoints](https://esi.tech.ccp.is/latest/#/Location)

**Comment by Kupuyc** [comment] 2017-09-05 17:27
Use case has been described in initial message, second paragraph. I need have list of all who online in alliance.

**Comment by SpeedProg** [comment] 2017-09-05 17:29
yeah and he just told you that there is already endpoints you can one for that.

**Comment by Kupuyc** [comment] 2017-09-05 17:33
Ok, I have 2500 characters in one alliance and 2000 in second. Tell me how to force them ALL give permission to ask their online status and you both are right. It's possible in theory but impossible in practice.

**Comment by SpeedProg** [comment] 2017-09-05 17:42
If you can't get them to give you that permission, that is your problem and definitively not one CCP should fix for you by making it impossible for them to not give it to you.
And doing even with 10k members retrieving the info would take you maybe like 20s. (kinda depends on how shit your code/connection is.)

**Comment by Robbilie** [comment] 2017-09-05 17:45
asking for the functionality is completely reasonable, the https://ccpgames.github.io/esi-issues/XML_to_ESI#membertracking endpoint and the ingame view reports the information, telling someone to use the character location endpoint is not helpful. all he is asking for is a lower cache time.

**Comment by Kupuyc** [comment] 2017-09-05 17:51
Yes, it's my problem.  And I asking CCP to help me. And it's just one small part of big mosaic - leaders of big alliances more than 10 years have no good tools to watch and manage their alliance members.

**Comment by iAddz** [comment] 2017-09-05 23:35
+1 to the alliance endpoint. It definitely plays into the corp/alliance overhaul that CCP Seagull has mentioned in the past. Providing more management tools to alliance leaders should be included.

It already has an in-game precedent with alliance chat memberlist and membercount.

**Comment by Kupuyc** [comment] 2017-10-13 05:41
Any news?

**Comment by Kupuyc** [comment] 2017-11-14 08:48
Any news?

**Comment by ccp-zoetrope** [comment] 2017-11-14 09:01
Coming into this with fresh eyes and having not been in the previous conversation, can you tell me exactly what news you're waiting for? It looks like this thread started out about corporation member online status, which got a recommendation for using other endpoints. Then it morphed into talking about alliance endpoints. Or are you waiting to hear about reducing the cache timer on the corporation member tracking endpoints? 

If it's about new alliance endpoints, please make a new issue about that. If it's about reducing the cache timer on the corporation member tracking endpoint then that would also be best as a new issue as well. If it's about making a whole new endpoint then....well that would also be good as a new issue that is more focused and has more specific details 😃.  I guess the conclusion to this comment is make a new issue 😆

**Comment by Kupuyc** [comment] 2017-11-14 09:27
``Thank you for response. 

> Or are you waiting to hear about reducing the cache timer on the corporation member tracking endpoints?

Long cache makes endpoint useless by my opinion. At least for purpose to check who where and what his online status *right now* or 5-10-15 mins ago. So, yes, shorter cache can help well.

But! In case ESI developers can do something what was described in start post it will be... PERFECT. Much better. Ideally. Some corporation endpoint like /corporations/{corporation_id}/online/ with cache 1-5 mins and list as result:
```
{
  "application/json": [
    {
      "character_id": 90000001,
      "online": true
    },
    {
      "character_id": 90000002,
      "online": false
    }
  ]
}
```

Another idea (see start post) - to extend /corporations/{corporation_id}/members/

**Comment by ccp-zoetrope** [comment] 2017-11-14 09:44
Please make a new issue specifically about lowering cache timer on the member tracking endpoint, it will be much easier to track 😄 Then you can also make an issue for your feature request for that new endpoint. Conversations can continue about each of these separately on those issues once you have made them.
