### ISSUE TITLE
Read/Write contact labels

### ISSUE THREAD

**Issue by NathenSample** [ccpgames/esi-issues#891] opened 2018-05-01 15:28 UTC
# Feature request

### Route
POST/PUT `/contacts/labels/`

### Authentication
Authenticated endpoint

### Use case
Creation of new labels on the user.
@antihax/Lucia both maintain contact management tools, notably this would facilitate better OOG management, and the ability to copy contacts from other characters where they use labels the current account does not.

### Route
GET `/contacts/labels/`

### Authentication
Authenticated endpoint

### Use case
Retrieval of created labels, and associated ID's
List existing labels, knowledge of when creation is required prior to use of a label in contact management software.

**Comment by CarbonAlabel** [comment] 2018-05-01 16:09
Duplicate of #173.

**Comment by NathenSample** [comment] 2018-05-01 16:10
ty @CarbonAlabel

**Comment by a-tal** [comment] 2018-05-02 22:07
I do appreciate the formatting here, but we should probs close to the older, more thumbup'd issue

**Closed by a-tal** 2018-05-02 22:07 UTC
Labels: duplicate
