### ISSUE TITLE
Invalid character ID in /v4/characters/ for freshly created characters

### ISSUE THREAD

**Issue by NomadThanatos** [ccpgames/esi-issues#569] opened 2017-09-25 03:35 UTC
# Bug

### Request
https://esi.tech.ccp.is/v4/characters/2113244947/

### Response
{"error": "Invalid character ID!"}

### Expected
https://esi.tech.ccp.is/v3/characters/2113244947/
{"corporation_id": 98185110, "birthday": "2017-09-24T11:54:38Z", "name": "Goodman Best", "gender": "male", "race_id": 8, "description": "", "bloodline_id": 7, "ancestry_id": 14, "security_status": 0.00035000000000000005}

**Comment by aquarhead** [comment] 2017-09-25 11:17
This is fixed now

**Comment by NomadThanatos** [comment] 2017-09-25 15:14
https://esi.tech.ccp.is/v4/characters/2113249773/
https://esi.tech.ccp.is/v3/characters/2113249773/

**Comment by aquarhead** [comment] 2017-09-25 15:37
Re-open with more detailed title

**Comment by cvweiss** [comment] 2017-09-26 02:49
I'm getting a few of these as well, v4 is returning invalid ID but v3 works:

https://esi.tech.ccp.is/v4/characters/2113251594/
https://esi.tech.ccp.is/v3/characters/2113251594/

**Comment by gitAskur** [comment] 2017-09-26 08:18
Logging the new character in should fix this.. but I figure since this is being reported that it does not. Guess I'll quickly take a look and see if I can close this quick.

I mean I wont clearly close this quick since I'll have to do the ritual of the deployment dance which takes days.

**Comment by gitAskur** [comment] 2017-09-26 08:20
Meh, easy enough to just clear it on character creation. Let's do that.

**Comment by gitAskur** [comment] 2017-09-26 09:19
Issue also exists from the other end - deleted characters do not get registered as such until after downtime.

**Comment by gitAskur** [comment] 2017-09-26 09:40
Fixed internally. Will do deployment dance later today.

**Comment by aquarhead** [comment] 2017-10-12 12:08
I just verified this should be fixed now:

https://esi.tech.ccp.is/v4/characters/2113311308/

fresh new capsuleer!!

**Comment by NomadThanatos** [comment] 2017-10-13 00:04
https://esi.tech.ccp.is/v4/characters/2113311544/
{"error":"Invalid character ID!"}
https://esi.tech.ccp.is/v3/characters/2113311544/
{"corporation_id":98517701,"birthday":"2017-10-12T12:44:47Z","name":"KevinLarson Li","gender":"female","race_id":1,"description":"","bloodline_id":11,"ancestry_id":33,"security_status":0.00035000000000000005}

**Comment by gitAskur** [comment] 2017-10-13 08:10
Confirmed. Taking a look.

**Comment by gitAskur** [comment] 2017-10-13 08:27
Probably an issue with machonet returning previously bound monikers for RPCs. There's no object for this character_id in his brokering service, so presumably the delete event processed fine but nothing has been instantiated since.

**Comment by gitAskur** [comment] 2017-10-13 11:49
Fiiiiiinally internally repro'd. Expect a fix out on Tuesday.

**Comment by aquarhead** [comment] 2017-10-17 11:28
https://esi.tech.ccp.is/v4/characters/2113329736/

This time I succeed in finding a new character created after DT

**Closed by aquarhead** 2017-10-17 11:28 UTC
Labels: bug, Staging
