### ISSUE TITLE
read/write character notes

### ISSUE THREAD

**Issue by NathenSample** [ccpgames/esi-issues#892] opened 2018-05-01 15:31 UTC
# Feature request

### Route
POST/PUT/GET `/characters/{character_id}/notes/`

### Authentication
Authenticated endpoint

### Use case
It is currently possible to manually enter notes about a character on their show-info page, it is impossible to mechanically read, or edit this information

## Note 
Some system, or alternative endpoint that would allow a wildcard return of all users you have stored notes about would also be incredibly useful should this be implemented.

**Comment by CarbonAlabel** [comment] 2018-05-01 16:09
Duplicate of #238.

**Comment by NathenSample** [comment] 2018-05-01 16:10
ty @CarbonAlabel

**Closed** 2018-05-02 22:06 UTC
Labels: duplicate
