### ISSUE TITLE
Support for HTTP HEAD requests

### ISSUE THREAD

**Issue by trixieflatline** [ccpgames/esi-issues#630] opened 2017-11-01 10:08 UTC
# Feature request

(nice to have)

### Route

Any

### Use case

Getting the HTTP Headers for a resource without fetching the Content. Example: Getting the `X-Pages` and `Expires` header for paged resources, to know in advance how many pages to fetch and when.

Right now, as @ccp-zoetrope explained on Slack, whether or not HEAD requests work depends on whether you're talking to the Google CDN (supports HEAD) or ESI directly (does not support HEAD, responds with "405 Method not Allowed"), so they can't be used in practice.

**Comment by lukasni** [comment] 2017-11-01 10:09
Duplicate of #629

**Closed** 2017-11-01 10:12 UTC
