### ISSUE TITLE
Feature Request: /ui/openwindow/givemoney/

### ISSUE THREAD

**Issue by Conjur0** [ccpgames/esi-issues#343] opened 2017-04-12 03:30 UTC
BACKGROUND/USAGE:
    Several alliances run SRP/Buyback/misc other payout services; that currently require people to copy/paste names/values/descriptions from a webpage, to the client. Personally, I run a buyback for one of the larger alliances, and have lost quite a bit due to my lack-luster copy/paste skills.

METHOD: POST
PARAMETERS: (preferably in content): character_id, amount, reason
SCOPE: esi-ui.open_window.v1

**Comment by Blacksmoke16** [comment] 2017-04-12 03:52
Duplicate of #190

**Comment by a-tal** [comment] 2017-05-02 16:32
closing this in favour of #190

**Closed by a-tal** 2017-05-02 16:32 UTC
Labels: New
