### ISSUE TITLE
rename get_characters_character_id_industry_jobs.response.station_id to location_id

### ISSUE THREAD

**Issue by guiguilechat** [ccpgames/esi-issues#819] opened 2018-03-28 11:20 UTC
I use a program in java that compiles the ESI.
Since some return types have the same structure, this allows to iterate over the results easily. Example, I can fetch the blueprints of corp and asset and use same function to handle them, because they have same structure. My compiler makes one inherit from the other.

However this is not the case for industry corp/char jobs.

 - corporation has long location_id
 - character has long station_id

I think the station_id should be replaced with location_id, it may have been  skipped when moving from int to long.
https://esi.tech.ccp.is/latest/#!/Industry/get_characters_character_id_industry_jobs

**Comment by itshouldntdothis** [comment] 2018-03-31 22:30
Appears to be a dupe of #604.

**Comment by ccp-zoetrope** [comment] 2018-04-03 09:22
Closing because this is a duplicate of https://github.com/ccpgames/esi-issues/issues/604.

**Closed by ccp-zoetrope** 2018-04-03 09:22 UTC
Labels: inconsistency
