### ISSUE TITLE
Feature Request: Expose mutated attributes in the contract items api.

### ISSUE THREAD

**Issue by Neugeniko** [ccpgames/esi-issues#906] opened 2018-05-10 09:25 UTC
Its gonna be hard to sell these items without some way to track them and their attributes.

**Comment by NathenSample** [comment] 2018-05-10 09:43
duplicate of #847

**Comment by ccp-zoetrope** [comment] 2018-05-11 10:55
Closing because this is a duplicate of https://github.com/ccpgames/esi-issues/issues/847 which also follows the issue template.

**Closed by ccp-zoetrope** 2018-05-11 10:55 UTC
