### ISSUE TITLE
Modify operationId's of published ESI endpoints

### ISSUE THREAD

**Issue by maurerit** [ccpgames/esi-issues#295] opened 2017-02-28 22:00 UTC
for an example: get_alliances_alliance_id_corporations doesn't really make a whole lot of sense.  The documentation for this function is:

```
List alliance's corporations
List all current member corporations of an alliance
```

This operation would make much more sense as get_alliance_corporations_by_alliance_id and would generate a java method named getAllianceCorporationsByAllianceId which in my opinion would be a much more palatable name.

This is only one such example.  This naming generated very unreadable code on the client side and spun off an effort to write a wrapper that wraps the swagger generated code (https://www.reddit.com/r/evetech/comments/5c3w7w/java_esi_client_library/).  If these names were readable and told a story in their brief life this would not be needed or desired.

**Comment by Robbilie** [comment] 2017-03-01 00:22
<http_method>_<tag>_<parameter>[_<remaining_path>] is not intuitive for you? :P 
i dont think its beautiful, but its functional, if i write code (JS, swagger-client, cant autocomplete) this style is really handy for me because i dont have to look up what crazy name some developer thought of if i know what i want (method, tag, param…)

**Comment by maurerit** [comment] 2017-03-01 01:03
No, it's not intuitive and I'm apparently not alone in this.  These are essentially data access methods and accessing them in a somewhat SQL like structure - get this from there where this is that - ie get... alliance_corporations... by_alliance_id makes perfect sense.  Representing a url in a string of text is not the optimal solution.

**Comment by SpeedProg** [comment] 2017-03-01 08:37
Names make very much sense through.
Maybe you just need to change the way you auto generate your method names, to not be so bad?

**Comment by maurerit** [comment] 2017-03-23 03:09
To generate a name of a function/method call based on the url that is used under the scenes is not a desired naming mechanism.  Without proper delimiters one doesn't know what part of the underlying url is what.

Generating a method/function name such as getAllianceCorporationsByAllianceId spells out EXACTLY what the developer would get and very easily tells them what their filter criteria is going to be.  Even better would be to make the function/method named: getCorporationsByAllianceId due to the fact that this function/method lives on an alliance_api client.

**Comment by antihax** [comment] 2017-03-23 03:16
I have to agree.. the names are a bit weird and complex. i.e.
`put_characters_character_id_calendar_event_id_internal_server_error` `post_characters_character_id_mail_labels_forbidden`
`get_corporations_corporation_id_members_200_ok`

**Comment by SpeedProg** [comment] 2017-03-23 11:07
I am just wondering what stops you guys from using something else (like the specified parameters and such) to generate names that fit your own opinion better, instead of trying to make ccp change their operatorIds.

**Comment by antihax** [comment] 2017-03-23 11:09
Example?

On Mar 23, 2017 06:07, "SpeedProg" <notifications@github.com> wrote:

I am just wondering what stops you guys from using something else (like the
specified parameters and such) to generate names that fit your own opinion
better, instead of trying to make ccp change their operatorIds.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ccpgames/esi-issues/issues/295#issuecomment-288686014>,
or mute the thread

**Comment by maurerit** [comment] 2017-03-28 15:20
@SpeedProg The generation is coming from code that we don't directly control.  Sure, we _could_ contribute to the generation code and start to make it even more complex than it already is but quite frankly it makes sane enough decisions as is as long as the swagger documentation has operationId's that are sane in the context in which they'll be consumed.

If you're hand coding your client, then this change wouldn't even begin to affect you as the operationId is strictly there for code generators.

The documentation of the swagger operationId usage:

_Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, **therefore, it is recommended to follow common programming naming conventions**._

That's all this issue is, a recommendation to revisit the operationId naming conventions so that they make more sense within the context that they're used.

**Comment by antihax** [comment] 2017-03-28 15:34
I think part of the issue is that the operation/model names are redundant with their service.

`get_corporations_corporation_members` is within the Corporations service.. so why is it not `get_corporation_members`?

**Comment by a-tal** [comment] 2017-03-28 15:44
the names are a result of the method and route. if someone has a suggestion that will still ensure unique IDs...

<img width="517" alt="screen shot 2017-03-28 at 8 41 36 am" src="https://cloud.githubusercontent.com/assets/1832772/24414212/8fe3e798-1392-11e7-8aaa-1830c90daf3d.png">

**Comment by antihax** [comment] 2017-03-28 16:09
I will dig around more when i get home, but swagger-codegen is magically producing and grouping everything into classes.

```
{{#operations}}
type {{classname}}Service service

{{#operation}}

/* {{{classname}}}Service {{summary}}{{#notes}}
 {{notes}}{{/notes}}

func (a *{{{classname}}}Service) {{{nickname}}} (Parameters) {
	...
}

{{/operation}}
{{/operations}}
```
Ends up as 
something along the lines of 

```func (a *CorporationApiService) GetCorporationsCorporationIdMembers( parameters )```

So `GetCorporationsCorporationIdMembers` is in namespace `CorporationApiService` making some of the name redundant.

Likewise the 500 errors are identical, and could really be just one model shared across other operations. I will dig a little more when i get home and see how possible this is.

**Comment by a-tal** [comment] 2017-11-03 20:11
some of this has been resolved with switching to models for common returns like forbidden, internal server errors, etc.

going to close this as in-actionable though, as I don't see any suggestion or reason to replace the existing `method_path_including_params` naming convention.

**Closed by a-tal** 2017-11-03 20:11 UTC

**Comment by maurerit** [comment] 2017-12-19 04:22
A naming convention was proposed in my opening comment.
