### ISSUE TITLE
Endpoint /ui/autopilot/waypoint/ Curl example fails

### ISSUE THREAD

**Issue by DavidEdwards** [ccpgames/esi-issues#229] opened 2017-01-19 20:12 UTC
The sample Curl line
===

https://esi.tech.ccp.is/latest/#!/User_Interface/post_ui_autopilot_waypoint

```
$ curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer SUPERSECRETTOKENGOESHERE' 'https://esi.tech.ccp.is/latest/ui/autopilot/waypoint/?destination_id=DESTINATIONIDHERE&clear_other_waypoints=true&add_to_beginning=true&datasource=tranquility'
```

Result
===
```
HTTP/1.0 411 Length Required
Content-Type: text/html; charset=UTF-8
Content-Length: 1564
Date: Thu, 19 Jan 2017 20:08:16 GMT

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 411 (Length Required)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>411.</b> <ins>That’s an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>
```

**Comment by a-tal** [comment] 2017-01-19 20:15
duplicate of #218

**Closed by a-tal** 2017-01-19 20:15 UTC
Labels: New
