### ISSUE TITLE
Search endpoint strict mode not filtering spaces properly

### ISSUE THREAD

**Issue by GunfighterJ** [ccpgames/esi-issues#486] opened 2017-07-10 02:28 UTC
# Bug
Using the `/search/` endpoint in strict mode, with a space in the query parameter will return results with a period (.) as well as with a space.

### Request
`https://esi.tech.ccp.is/latest/search/?categories=corporation&datasource=tranquility&language=en-us&search=Evil%20Guardians&strict=true`

### Response
`{"corporation": [98180443, 98375162]}`
### Expected
`{"corporation": [98375162]}`

### Description
In this example, searching for `Evil Guardians` on the `/search/` endpoint for corporations with strict mode enabled yields a result containing both corporations `Evil Guardians` and `evil.guardians`. From a user's perspective it would make sense if a space and a period were not seen as synonymous.

**Comment by SpeedProg** [comment] 2017-07-10 07:47
an other duplicate of #211

**Comment by GunfighterJ** [comment] 2017-07-10 11:53
Wow does it really take 7 months to fix this?

**Comment by fuzzysteve** [comment] 2017-07-10 11:54
I _suspect_ this is a print-join issue, with the tokenizer.

That can be complicated to fix.

**Comment by SpeedProg** [comment] 2017-07-10 11:55
> Wow does it really take 7 months to fix this?

Maybe they think search isn't use much anyway, because at least you didn't, before posting this.

**Comment by GunfighterJ** [comment] 2017-07-10 12:01
I've been using it quite a bit, but it was finally pointed out today that the corp name didn't match the corp ID.

**Comment by aquarhead** [comment] 2017-07-11 13:58
Closing as a duplicate of #211 

The "search" functionalities in EVE is under heavy refactor, we would migrate search endpoints to the new system and hopefully get this fixed.

**Closed by aquarhead** 2017-07-11 13:58 UTC
Labels: New
