### ISSUE TITLE
Eve Swagger OAuth2.0 scopes authorizations - too many scopes

### ISSUE THREAD

**Issue by Pseudocode99** [ccpgames/esi-issues#519] opened 2017-08-21 18:50 UTC
If i select too many scopes in the authorization window (https://esi.tech.ccp.is/latest/) i get always a 

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

How to avoid this, if for example i would like to select all scopes?
-Browser: Edge-

Thanks

**Comment by Blacksmoke16** [comment] 2017-08-22 01:16
Duplicate of #267

Workaround for now: is to have to user login first, 

Example:

1. Login at https://login.eveonline.com/
2. Click the `Login with EVE Onlin` button
3. Logoff at https://login.eveonline.com/Account/LogOff
4. Repeat

**Comment by Makeshift** [comment] 2017-08-22 01:19
Is there a workaround possible while using Postman? I couldn't figure one out.

**Comment by Blacksmoke16** [comment] 2017-08-22 01:21
Not AFAIK.  Probably could slim down the number of scopes you request tho.  Some of the are CREST specific, and/or duplicated in ESI.  See if you get any luck using only the esi-xxxx ones.

**Comment by aquarhead** [comment] 2017-08-29 10:35
Duplicate of #267

**Closed by aquarhead** 2017-08-29 10:35 UTC
