### ISSUE TITLE
Invalid 403 from GET /corporations/{corporation_id}/roles/

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#417] opened 2017-05-27 18:40 UTC
# Bug

### Request
`curl -i --compressed -X GET --header 'Accept: application/json' --header 'Authorization: Bearer Access_Token' 'https://esi.tech.ccp.is/latest/corporations/98466507/roles/?datasource=tranquility'`

### Response

```
{
  "error": "Character not in corporation"
}

```

```
{
  "date": "Sat, 27 May 2017 18:32:26 GMT",
  "via": "1.1 google",
  "last-modified": "Sat, 27 May 2017 18:32:26 GMT",
  "access-control-allow-origin": "*",
  "access-control-max-age": "600",
  "access-control-allow-methods": "GET,OPTIONS",
  "content-type": "application/json",
  "status": "403",
  "alt-svc": "clear",
  "access-control-expose-headers": "Content-Type,Warning",
  "cache-control": "private",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "content-length": "41",
  "expires": "Sat, 27 May 2017 18:50:36 GMT"
}
```
### Expected

Roles of Character in my corporation. (Actually there is only one character, but this should still return that characters roles.)

This char is the CEO of the corporation as well

https://esi.tech.ccp.is/latest/characters/96154467/?datasource=tranquility

```
{
  "corporation_id": 98466507,
  "birthday": "2016-01-10T23:51:35Z",
  "name": "SuperFun Guy",
  "gender": "male",
  "race_id": 1,
  "bloodline_id": 11,
  "description": "",
  "ancestry_id": 32,
  "security_status": 0
}
```

https://esi.tech.ccp.is/latest/corporations/98466507/?datasource=tranquility
```

{
  "corporation_name": "House of Davaham",
  "ticker": "DAVAH",
  "member_count": 1,
  "ceo_id": 96154467,
  "corporation_description": "Enter a description of your corporation here.",
  "tax_rate": 0,
  "creator_id": 95923084,
  "url": "http://",
  "creation_date": "2016-06-23T23:45:10Z"
}
```

### Edit

Remove Access Token

**Comment by a-tal** [comment] 2017-05-29 21:10
re #416

**Comment by aquarhead** [comment] 2017-08-23 12:35
The corporation in question is gone, is this still an issue? I can't reproduce this CEO not in response error in my local development environment.

**Comment by ddouglas493** [comment] 2017-08-29 01:24
I no longer have a character that is the CEO of a corporation sadly, so I am unable to test this. I apologize.

**Comment by aquarhead** [comment] 2017-08-29 10:30
Closing this due to not able to reproduce

**Closed by aquarhead** 2017-08-29 10:30 UTC
Labels: bug, esi-corporations, New
