### ISSUE TITLE
/universe/structures/{structure_id}/ - public structures sometimes return 403

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#81] opened 2016-11-13 10:14 UTC
I received a 403 response when requesting citadel 1021011818054 (Perimeter - Verite's Stellar Cartography). However I visited the structure immediately afterwards and was able to dock there.

**Comment by tsuthers-ccpgames** [comment] 2016-11-24 16:10
I cannot repro with the provided citadel ID. I've been running a dodgy script locally to test, and the only 403's I get are when the script runs longer than 20 minutes, and my token expires.

Could you confirm the issue is still present with that specific citadel?

**Comment by wtfrank** [comment] 2016-11-24 21:49
I'm not getting a 403 on that citadel now.

However I am getting a lot of 403s and 500s on other structures very soon after refreshing the access token, which I think rules access tokens out. These structure ids all came from the public structures endpoint shortly beforehand. Its not consistent from run to run however. two hours later I ran the same script again and found a different set of structures were failing.

For example, 1021017648419 and 1021018581901 failed with 403 at 19:05 and 1021023441161 failed with 500, but all were retrieved successfully later on.

Below I present two sets of results from around 7pm and 9pm.

access token refreshed: 2016-11-24 19:05:02.666949+00:00
1021017648419 403 403 FORBIDDEN 2016-11-24 19:05:25.087712+00:00
1021018581901 403 403 FORBIDDEN 2016-11-24 19:05:35.221033+00:00
1021019702897 403 403 FORBIDDEN 2016-11-24 19:05:46.930915+00:00
1021023441161 500 500 INTERNAL SERVER ERROR 2016-11-24 19:06:03.265359+00:00
1021049832391 403 403 FORBIDDEN 2016-11-24 19:06:35.984467+00:00
1021049832391 403 403 FORBIDDEN 2016-11-24 19:06:36.091419+00:00
1021049971293 500 500 INTERNAL SERVER ERROR 2016-11-24 19:06:47.527873+00:00
1021079239381 403 403 FORBIDDEN 2016-11-24 19:08:00.258957+00:00
1021100611270 403 403 FORBIDDEN 2016-11-24 19:08:38.720915+00:00
1021106463996 500 500 INTERNAL SERVER ERROR 2016-11-24 19:09:00.274349+00:00
1021124677920 403 403 FORBIDDEN 2016-11-24 19:09:26.801230+00:00
1021130347457 403 403 FORBIDDEN 2016-11-24 19:09:43.635358+00:00
1021138482138 500 500 INTERNAL SERVER ERROR 2016-11-24 19:10:01.647098+00:00
1021155703371 403 403 FORBIDDEN 2016-11-24 19:10:31.229235+00:00
1021158501548 403 403 FORBIDDEN 2016-11-24 19:10:43.444503+00:00
1021173810982 500 500 INTERNAL SERVER ERROR 2016-11-24 19:11:07.298264+00:00
1021175472863 403 403 FORBIDDEN 2016-11-24 19:11:18.835652+00:00
1021179953976 500 500 INTERNAL SERVER ERROR 2016-11-24 19:11:32.343854+00:00
1021214185430 500 500 INTERNAL SERVER ERROR 2016-11-24 19:12:11.189070+00:00
1021218475361 403 403 FORBIDDEN 2016-11-24 19:12:23.467128+00:00
1021229436008 403 403 FORBIDDEN 2016-11-24 19:12:38.982302+00:00
1021237759122 403 403 FORBIDDEN 2016-11-24 19:12:56.816350+00:00
1021241847324 403 403 FORBIDDEN 2016-11-24 19:13:09.721557+00:00
1021259975959 500 500 INTERNAL SERVER ERROR 2016-11-24 19:13:34.212784+00:00
1021273116563 500 500 INTERNAL SERVER ERROR 2016-11-24 19:13:54.844161+00:00
1021279780158 500 500 INTERNAL SERVER ERROR 2016-11-24 19:14:08.467040+00:00
1021331132117 500 500 INTERNAL SERVER ERROR 2016-11-24 19:14:58.690525+00:00
1021378064393 500 500 INTERNAL SERVER ERROR 2016-11-24 19:15:33.824328+00:00
1021443992625 403 403 FORBIDDEN 2016-11-24 19:16:25.569923+00:00
1021463402831 500 500 INTERNAL SERVER ERROR 2016-11-24 19:16:49.021757+00:00
1021467709445 500 500 INTERNAL SERVER ERROR 2016-11-24 19:17:01.811109+00:00
1021475665614 403 403 FORBIDDEN 2016-11-24 19:17:16.906529+00:00
1021477887051 500 500 INTERNAL SERVER ERROR 2016-11-24 19:17:27.891806+00:00
1021491008281 500 500 INTERNAL SERVER ERROR 2016-11-24 19:17:47.057968+00:00
1021492209728 403 403 FORBIDDEN 2016-11-24 19:17:57.215823+00:00
1021501687148 403 403 FORBIDDEN 2016-11-24 19:18:13.238774+00:00
1021568516963 403 403 FORBIDDEN 2016-11-24 19:18:57.312639+00:00
1021627376828 500 500 INTERNAL SERVER ERROR 2016-11-24 19:19:40.446456+00:00
1021752083693 403 403 FORBIDDEN 2016-11-24 19:20:58.609204+00:00
1021802713586 500 500 INTERNAL SERVER ERROR 2016-11-24 19:21:34.280075+00:00
...



access token refreshed: 2016-11-24 21:06:15.977918+00:00
1021019276382 500 500 INTERNAL SERVER ERROR 2016-11-24 21:06:59.361096+00:00
1021031713981 500 500 INTERNAL SERVER ERROR 2016-11-24 21:07:23.689001+00:00
1021051905214 403 403 FORBIDDEN 2016-11-24 21:07:53.549630+00:00
1021057442671 500 500 INTERNAL SERVER ERROR 2016-11-24 21:08:16.365698+00:00
1021086426526 403 403 FORBIDDEN 2016-11-24 21:09:15.473811+00:00
1021096761041 500 500 INTERNAL SERVER ERROR 2016-11-24 21:09:41.037013+00:00
1021097310581 500 500 INTERNAL SERVER ERROR 2016-11-24 21:09:52.009619+00:00
1021099561831 403 403 FORBIDDEN 2016-11-24 21:09:53.374254+00:00
1021101666692 500 500 INTERNAL SERVER ERROR 2016-11-24 21:10:05.565371+00:00
1021172044645 500 500 INTERNAL SERVER ERROR 2016-11-24 21:10:58.161593+00:00
1021179849103 403 403 FORBIDDEN 2016-11-24 21:11:01.124511+00:00
1021194936479 500 500 INTERNAL SERVER ERROR 2016-11-24 21:11:17.501846+00:00
1021305454410 500 500 INTERNAL SERVER ERROR 2016-11-24 21:12:14.742549+00:00
1021476688237 500 500 INTERNAL SERVER ERROR 2016-11-24 21:13:20.130203+00:00
1021506347588 500 500 INTERNAL SERVER ERROR 2016-11-24 21:13:39.855339+00:00
1021515590164 500 500 INTERNAL SERVER ERROR 2016-11-24 21:13:51.749543+00:00
1021565307255 403 403 FORBIDDEN 2016-11-24 21:14:04.136111+00:00
1021569098538 500 500 INTERNAL SERVER ERROR 2016-11-24 21:14:14.510863+00:00
1021637601895 403 403 FORBIDDEN 2016-11-24 21:14:32.395554+00:00
1021671573338 403 403 FORBIDDEN 2016-11-24 21:14:38.571617+00:00
1021683079978 500 500 INTERNAL SERVER ERROR 2016-11-24 21:14:51.885564+00:00

**Comment by Ligraph** [comment] 2016-11-27 07:20
I'm having a similar issue getting structure data for outposts and stations that I can dock in, specifically the structure ID 60006682 (Fensi VII).  Something interesting I noted is that it does show up through /characters/{character_id}/search/.

**Comment by nicebits** [comment] 2017-07-29 02:54
I can confirm these symptoms for both citadels and NPC stations.  Reproducing using both my custom client and the swagger test site hosted by CCP results in the following behavior:

Condition 1: No authentication header provided
Query: GET /latest/universe/structures/61000318
Result from swagger test site: valid structure data
Result from custom client: valid structure data

Condition 2: Authentication header provided with a token for all scopes
Query: GET /latest/universe/structures/61000318
Result from swagger test site: 502 Could not determine docking access
Result from custom client: 502 Could not determine docking access

Condition 3: Authentication header provided with a token for all scopes
Query: GET /latest/universe/structures/1023697976234
Result from swagger test site: 403 Forbidden
Result from custom client: 403 Forbidden

**Comment by tsuthers-ccpgames** [comment] 2018-01-05 13:58
So this is partly me being terrible with my paperwork. The original cause of this was that we weren't taking banned characters into account with the public endpoint.

So we listed every structure that had the "public" user in it's allowed ACL, but then some structures were public except that they banned this or that alliance.

The result was that some users from those alliances would crawl the "public" structures and then get 403's from the ones they were banned from. This was fixed by changing the criteria for what constituted a public citadel to be "has the 'public' user and also doesn't ban anyone".  That was done like...January last year, but I never closed this ticket.

@Ligraph and @nicebits The /structures/{structure_id}/ is not for stations or outposts, it is only for new-style structures (citadels, engineering complexes, refineries).

Most of the stuff you guys have listed is for stations, I can tell because they are in the in32 range, all structures have an int64 id. If you're still seeing these issues with new-style structures, could you please open a new ticket with current details?

Cheers, sorry for the crazy delay 😞

**Closed by tsuthers-ccpgames** 2018-01-05 13:58 UTC
Labels: Backlog, bug, esi-universe
