### ISSUE TITLE
Bug in: get /characters/{character_id}/orders/

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#392] opened 2017-05-14 08:16 UTC
# Bug

### Request
I'm getting: Unhandled internal error encountered!
On the ```get /characters/{character_id}/orders/``` endpoint
Not sure why...

### Response
Response Body:
```
{
  "error": "Unhandled internal error encountered!"
}
```

Response Code:
```
500
```

Response Headers:
```
{
  "server": "nginx",
  "date": "Sun, 14 May 2017 08:05:04 GMT",
  "content-type": "application/json",
  "content-length": "50",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "access-control-allow-methods": "GET,POST,DELETE,PUT,PATCH,OPTIONS",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Content-Type,Warning",
  "access-control-max-age": "600",
  "vary": "Accept-Encoding",
  "strict-transport-security": "max-age=31536000",
  "via": "1.1 google",
  "alt-svc": "clear",
  "x-firefox-spdy": "h2"
}
```

### Expected
```[]```
or
The active market orders

**Comment by itshouldntdothis** [comment] 2017-05-14 08:57
Duplicate of #383.

**Closed** 2017-05-18 19:47 UTC
Labels: duplicate, New
