### ISSUE TITLE
Minor inconsistency in Market Orders (Between corp and char)

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#605] opened 2017-10-16 08:19 UTC
# Inconsistency

### Routes
https://esi.tech.ccp.is/dev/?datasource=tranquility#!/Market/get_characters_character_id_orders
https://esi.tech.ccp.is/dev/?datasource=tranquility#!/Market/get_corporations_corporation_id_orders

### Description
Corporation: `wallet_division (integer): Wallet division of which this order used `
Character: `account_id (integer): Wallet division for the buyer or seller of this order. Always 1000 for characters. Currently 1000 through 1006 for corporations ,`

### Resolution
Use `wallet_division (integer): Wallet division of which this order used` in both endpoints
Maybe use some of the description from the character in both endpoints, something like:
`Wallet division used for this order. Always 1000 for characters. Currently 1000 through 1006 for corporations`

**Comment by aquarhead** [comment] 2017-10-17 11:08
Duplicate of #396

**Closed by aquarhead** 2017-10-17 11:08 UTC
