### ISSUE TITLE
esi-alliances: clarifiction: closed alliance with executor_corp but no corporations

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#253] opened 2017-02-01 13:52 UTC
how does this happen?
alli is closed, optional executor_corp is set, corporations returns empty array

**Comment by Robbilie** [comment] 2017-02-01 13:55
exec corp ceo biomassed?

**Comment by a-tal** [comment] 2017-05-02 17:54
what's the alliance ID in question here?

**Comment by Robbilie** [comment] 2017-05-03 14:57
just so it doesnt get lost in slack logs again:
example id:
264679431
https://esi.tech.ccp.is/latest/alliances/264679431/
https://esi.tech.ccp.is/latest/alliances/264679431/corporations/

**Comment by aquarhead** [comment] 2017-08-10 13:16
Might be we didn't clean up old database records, tagging @gitAskur to check whether we need to clean up these things or not.

**Comment by gitAskur** [comment] 2017-09-05 08:59
Pretty sure this should be solved by not returning alliances that no longer exist in game, but let me clear that up with game design.

Otherwise, i'm inclined to just close this as this is denormalized data being left alone after a record is marked as "dead". I could also fix the data so that this is nulled on alliance delete and that sounds so super easy so that it definitely is a cluster bomb dressed up with a friendly face and this value is now actually super important for deleted alliances because of some super voodoo reason but if you mess with it PoS's will start shooting at blues.

**Comment by Robbilie** [comment] 2017-09-05 09:56
Wowowowow not returning dead alliances wtf pls no. That would mean you couldn't resolve so many references.

**Comment by gitAskur** [comment] 2017-09-05 10:10
It would of course function as the client does, by returning a name and relevant information as such, but not dead and irrelevant information like what state some value was in when the alliance closed down.

I do not hate foreign key references, just denormalized ghost values.

**Comment by gitAskur** [comment] 2017-09-06 10:00
So having talked to game design and looked at the in client information available this seems functioning as intended. Show Info on a deleted alliance in your corps alliance history and you will see the Executor Corp detail filled with the last corp that was there and the member list will be empty.

So I am going to close this, but do feel free to comment here explaining the issue better if I misunderstood this.

**Closed by gitAskur** 2017-09-06 10:00 UTC
Labels: Backlog, bug, esi-alliances
