### ISSUE TITLE
Star not found

### ISSUE THREAD

**Issue by AdrienCS** [ccpgames/esi-issues#658] opened 2017-11-17 09:42 UTC
# Inconsistency

### Routes
GET /universe/stars/{star_id}/ 

### Description
The system **Senda** (30020141) return 
```json
{
  "star_id": 40342401, 
}
```

which is not found in the route above.

```shell
https://esi.tech.ccp.is/latest/universe/stars/40342401/?datasource=tranquility
```

```json
{
  "error": "Star not found"
}
```

(from the old CREST, the system has a sunTypeID = 3796)

**Comment by itshouldntdothis** [comment] 2017-11-17 10:12
dupe of #532 it would appear

**Comment by ccp-zoetrope** [comment] 2017-11-17 10:30
I'm going to close this because it is a duplicate :)

**Closed by ccp-zoetrope** 2017-11-17 10:30 UTC
