### ISSUE TITLE
Feature Request: Renaming and Moving Bookmarks via API

### ISSUE THREAD

**Issue by Lucius-Q-User** [ccpgames/esi-issues#529] opened 2017-08-29 11:35 UTC
# Feature request
Allow using PUT requests to update bookmark data. (Move bookmarks between folders, rename bookmarks, set bookmark notes)
### Route
    /characters/{character_id}/bookmarks/{bookmark_id}/
### Authentication
SSO
### Use case
Allow wormhole mapping tools to automatically mark EOL holes, delete out of date locations, auto sort bookmarks in folders
### Example request model
    {
        "folder_id": 5,
         "memo": "*C5/J123/GAY (EOL)",
         "note": ""
    }
### Example returns
204: Bookmark updated
403: Forbidden

    {
        "error": "string",
        "sso_status": 0
    } 
### Previous XML or CREST route
N/A

**Comment by aquarhead** [comment] 2017-08-29 12:17
Duplicate of #69

**Closed by aquarhead** 2017-08-29 12:17 UTC
