### ISSUE TITLE
[Bug] 502 malformed as HTML rather than JSON

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#902] opened 2018-05-05 13:25 UTC
# Bug

When requesting a fleet's members, I receive an malformed 502 error.

## Request

`GET /v1/fleets/{fleet_id}/members/`

### Status Code

`502`

### Headers

```
            [0] => HTTP/1.1 502 Bad Gateway
            [1] => Server: awselb/2.0
            [2] => Date: Sat, 05 May 2018 02:36:48 GMT
            [3] => Content-Type: text/html
            [4] => Content-Length: 138
            [5] => Connection: keep-alive
```

### Body

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

## Expected

The spec described a JSON body, with the given example:

```
{
  "error": "Bad gateway message"
}
```

The same error previously occured `Date: Fri, 04 May 2018 01:06:28 GMT`.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by antihax** [comment] 2018-05-05 13:33
This is a CDN error from the load balancer, not a cluster error.

Just retry the request later.

**Comment by DaneelTrevize** [comment] 2018-05-05 13:43
The bug isn't the error occuring, it's the error not being per spec. It's spitting HTML rather than JSON.

**Comment by Chnkr** [comment] 2018-05-05 13:56
I believe AWS does not even allow custom error pages, just back off and retry again

**Comment by a-tal** [comment] 2018-05-07 21:54
this is outside of our control, also a duplicate of #530

**Closed by a-tal** 2018-05-07 21:54 UTC
Labels: duplicate
