### ISSUE TITLE
esi-corporations: current pilots online

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#10] opened 2016-11-09 16:43 UTC
https://trello.com/c/WEeDo0Iw/39-esi-corporations-current-pilots-online

**Comment by ccpStuart** [comment] 2016-12-06 15:17
reviewed

**Comment by ccpStuart** [comment] 2016-12-06 15:29
Duplicate of https://github.com/ccpgames/esi-issues/issues/52

**Closed** 2016-12-06 15:29 UTC
Labels: Backlog, esi-corporations
